name: feg_cli
description: A CLI for generate flutter templates
version: 0.0.1-dev.1
repository: https://github.com/fegno/feg_cli
topics: [cli, codegen, test, template, boilerplate]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.5.0
  mason: ^0.1.0-dev.57
  mason_logger: ^0.2.5
  path: ^1.9.0
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^6.0.0

executables:
  feg_cli:
