name: feg_cli
description: A CLI for generate flutter templates
version: 0.0.1-dev.4
repository: https://github.com/fegno/feg_cli
topics: [cli, codegen, test, template, boilerplate]
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.5.0
  mason: ^0.1.0-dev.57
  mason_logger: ^0.3.3
  path: ^1.9.0
  pub_updater: ^0.5.0
  #*Mono repos
  app_name_changer:
    path: packages/app_name_changer
  app_package_name_changer:
    path: packages/app_package_name_changer

  #* Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^7.0.0

  #*Code Generation
  freezed: ^3.0.3
  json_serializable: ^6.9.4

executables:
  feg_cli:
